# Generated by Django 5.0.3 on 2024-03-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg_templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='message_content',
            new_name='content',
        ),
    ]
