# Generated by Django 5.0.3 on 2024-03-24 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('message_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientlog',
            name='contact_id',
            field=models.ForeignKey(db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact'),
        ),
    ]
