# Generated by Django 5.0.3 on 2024-03-21 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('sent_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Log',
                'verbose_name_plural': 'Message Logs',
                'db_table': 'message log',
            },
        ),
        migrations.CreateModel(
            name='ReceipientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(db_column='receipient', on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('message', models.ForeignKey(db_column='message', on_delete=django.db.models.deletion.CASCADE, to='messages_logs.messagelog')),
            ],
            options={
                'verbose_name': 'Receipient Log',
                'verbose_name_plural': 'Receipient Logs',
                'db_table': 'receipient log',
            },
        ),
    ]
