# Generated by Django 5.0.3 on 2024-03-22 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('messages_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='author',
            field=models.ForeignKey(db_column='authorId', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipientlog',
            name='contact',
            field=models.ForeignKey(db_column='receipient', on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='recipientlog',
            name='message',
            field=models.ForeignKey(db_column='message', on_delete=django.db.models.deletion.PROTECT, to='messages_logs.messagelog'),
        ),
    ]
