# Generated by Django 5.0.3 on 2024-03-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('messages_logs', '0002_alter_messagelog_author_alter_recipientlog_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipientlog',
            options={'verbose_name': 'Recipient Log', 'verbose_name_plural': 'Recipient Logs'},
        ),
        migrations.AlterField(
            model_name='recipientlog',
            name='contact',
            field=models.ForeignKey(db_column='receipient', on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='recipientlog',
            name='message',
            field=models.ForeignKey(db_column='message', on_delete=django.db.models.deletion.CASCADE, to='messages_logs.messagelog'),
        ),
        migrations.AlterModelTable(
            name='recipientlog',
            table='recipient_log',
        ),
    ]
